# 数据源配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_dongli
    username: 
    password: 
  redis:
    host: l
    port: 6379
server:
  port: 8081

rtdb:
  host: localhost
  port: 8086

calc:
  interval: 120
